version: "3.9"

services:
  task_db:
    image: postgres:15
    container_name: psql
    restart: always
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vitask.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - task_db

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile.backend
#    container_name: vitask-backend
#    restart: always
#    environment:
#      DB_HOST: task_db
#      DB_USER: admin
#      DB_PASSWORD: admin
#      DB_NAME: task_db
#      DB_PORT: 5432
#    ports:
#      - "3000:3000"
#    depends_on:
#      - task_db
#
#  frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile.frontend
#    container_name: vitask-frontend
#    restart: always
#    ports:
#      - "3001:3000"
#    depends_on:
#      - backend

volumes:
  pgdata:
